# Generated by Django 4.2.2 on 2023-06-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_alter_estudiante_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'modulo')},
        ),
    ]
